version: '3'
services:
    node:
        build:
            context: app_node
            dockerfile: dev.Dockerfile
        environment:
            TZ: America/Mexico_City
            PORT: 3000
            PROXY_PORT: 80
            PROXY_HOST: "localhost"
            HOST: "node"
            TOKEN_EXPIRETIME: 3600
            TOKEN_ISSUER: "isvaku"
            TOKEN_SECRET: "my-very-secret-key"
            SANDBOX: "true"
            CHINA: "false"
            API_CONSUMER_KEY: your_evernote_consumer_key
            API_CONSUMER_SECRET: your_evernote_consumer_secret
            MONGODB_PORT: 27017
            MONGODB_USERNAME: flaskuser
            MONGODB_PASSWORD: password
            MONGODB_HOSTNAME: mongodb
            MONGODB_DATABASE: flaskdb
        ports:
            - "9229:9229"

    mongodb:
        environment:
            TZ: America/Mexico_City
            MONGO_INITDB_ROOT_USERNAME: mongodbuser
            MONGO_INITDB_ROOT_PASSWORD: your_mongodb_root_password

    webserver:
        environment:
            TZ: America/Mexico_City
            APP_ENV: "dev"
            APP_NAME: "webserver"
            APP_DEBUG: "false"
            SERVICE_NAME: "webserver"

    mongo_express:
        environment:
            ME_CONFIG_OPTIONS_EDITORTHEME: 3024-night
            ME_CONFIG_BASICAUTH_USERNAME: mongoexpress
            ME_CONFIG_BASICAUTH_PASSWORD: mongoexpress
            ME_CONFIG_MONGODB_ADMINUSERNAME: mongodbuser
            ME_CONFIG_MONGODB_ADMINPASSWORD: your_mongodb_root_password
            ME_CONFIG_MONGODB_SERVER: mongodb